# Generated by Django 5.0.6 on 2024-06-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_nom_tuteur_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='nom_enfant',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_enfant',
            field=models.IntegerField(default=0),
        ),
    ]
