# Generated by Django 5.0.6 on 2024-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nom_tuteur',
            new_name='ville_residence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age_enfant',
        ),
        migrations.AddField(
            model_name='profile',
            name='ecole',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville_naissance',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
