# Generated by Django 5.0.6 on 2024-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_phone_number_profile_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_enfant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
